development:
  adapter: postgresql
  encoding: unicode
  database: trip_captain_development
  pool: 5 

test:
  adapter: postgresql
  encoding: unicode
  database: trip_captain_test
  pool: 5 

production:
  adapter: postgresql
  encoding: unicode
  database: trip_captain_production
  pool: 5 


